# Generated by Django 4.0.4 on 2022-06-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog_app', '0002_alter_post_img_alter_post_user_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название контакта')),
                ('contact_url', models.URLField(unique=True, verbose_name='Ссылка на контакт')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания контакта')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления контакта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'unique_together': {('name', 'contact_url')},
            },
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Пост'),
        ),
    ]
